---
title: "Clean Purchase Orders"
format: html
---

```{r}
library(tidyverse)
library(glue)
library(janitor)
library(readxl)
library(writexl)

options(scipen = 12, digits = 12)
```

Setup

```{r}
path_data <- glue(
  "C:/Users",
  "{Sys.getenv('USERNAME')}",
  "OneDrive - District of Columbia Public Schools",
  "Data",
  .sep = "/"
)

fy <- "2024"

dir_r071 <- glue("{path_data}/Purchase Orders/R071/raw/{fy}")

path_r209 <-
  glue("{path_data}/Budget/R209/raw/{fy}/r209_GD0_GA0_{fy}.xlsx")

path_r071_ga0 <-
  glue("{dir_r071}/r071_GA0_{fy}.xls")

path_r071_gd0 <-
  glue("{dir_r071}/r071_GD0_{fy}.xls")

path_r071 <-
  glue("{dir_r071}/r071_{fy}.xls")
```

Read

209

```{r}
r209_raw <-
  read_excel(path_r209, col_types = "text", range = "A17:AG5216") %>%
  clean_names()

r209 <- r209_raw
```

R071

```{r}
# r071_ga0 <-
#   read_excel(path_r071_ga0, col_types = "text", range = "A23:AY8171") %>%
#   clean_names()
#
# r071_gd0 <-
#   read_excel(path_r071_gd0, col_types = "text", range = "A23:AY5118") %>%
#   clean_names()
#
# r071_raw <- bind_rows(r071_ga0, r071_gd0)

r071_raw <-
  read_excel(path_r071, col_types = "text", range = "A23:AY29404") %>%
  clean_names()

r071 <- r071_raw
```

Rename

```{r}
r071_rename <- r071
```

Clean and transform

```{r}
pos <-
  r071_rename %>%
  filter(buyer_agency == "GA0" | (project %in% r209$project)) %>%
  group_by(po_number, po_title) %>%
  summarize(
    po_line_item_description = str_flatten(
      sort(unique(po_line_item_description))[1:3],
      collapse = "; ",
      na.rm = TRUE
    ),
  ) %>%
  select(
    po_number, po_title, po_line_item_description,
  ) %>%
  arrange(
    po_number, po_title, po_line_item_description,
  )
```

Write purchase orders

```{r}
pos %>% write_xlsx("data/pos.xlsx")
```
