---
title: "Clean Ledger"
format: html
---

# Setup

```{r}
library(tidyverse)
library(glue)
library(janitor)
library(readxl)
library(writexl)
library(arrow)

options(scipen = 12, digits = 12)

path_data <- Sys.getenv("PATH_DATA")
year_fiscal <- Sys.getenv("YEAR_FISCAL")
```

# Import

```{r}
r209 <-
  read_excel(
    glue("{path_data}/raw/r209_GD0_GA0_{year_fiscal}.xlsx"),
    range = "A17:AG3974", col_types = "text"
  ) |>
  clean_names() |>
  rename(project_id = project)

r023_ga0 <-
  read_excel(
    glue("{path_data}/raw/r023_expense_GA0_{year_fiscal}.xls"),
    range = "A15:AL64383", col_types = c(rep("text", 35), rep("numeric", 3))
  )

r023_gd0 <-
  read_excel(
    glue("{path_data}/raw/r023_expense_GD0_{year_fiscal}.xls"),
    range = "A15:AL11651", col_types = c(rep("text", 35), rep("numeric", 3))
  )

ledger <-
  bind_rows(r023_ga0, r023_gd0) |>
  clean_names() |>
  rename(
    agency_id = agency,
    fund_id = fund_detail, fund_name = fund_detail_desc,
    program_id = program, program_name = program_desc,
    costcenter_id = cost_center, costcenter_name = cost_center_desc,
    account_id = account, account_name = account_desc,
    project_id = project, project_name = project_desc,
    award_id = award, award_name = award_desc
  ) |>
  filter(agency_id == "GA0" | ((project_id %in% r209$project_id))) |>
  mutate(
    costcenter_id = if_else(
      program_id == "150011", "PAYROLL DEFAULT", costcenter_id
    ),
    costcenter_name = if_else(
      program_id == "150011", "PAYROLL DEFAULT", costcenter_name
    ),
  )
```

"Compiled General Ledger" document for submission

```{r}
ledger |>
  write_csv(
    glue("{path_data}/schedules/3.1 Compiled General Ledger.csv"),
    na = ""
  )
```

# Tidy

```{r}
ledger <-
  ledger |>
  mutate(
    is_nonbudgetary = (award_id == "9999998"),
    is_osse = (agency_id == "GD0"),
    is_summeradvance = (fund_id %in% c("1010171", "1010173")),
    is_capital = (appropriation_fund == "3030"),
    is_medicaid = (fund_id == "4020999" & award_id == "2000276"),
  )
```

```{r}
ledger |> write_parquet(glue("{path_data}/working/ledger.parquet"))
```

```{r}
ledger |>
  distinct(costcenter_name, costcenter_id) |>
  arrange(costcenter_name) |>
  write_csv(glue("{path_data}/working/costcenters.csv"))
```

```{r}
ledger |>
  filter(account_category == "710000A") |>
  distinct(account_name, account_id) |>
  arrange(account_name) |>
  write_csv(glue("{path_data}/working/accounts.csv"))
```

# Diagnostic

Budgetary basis expenditures from ACFR (thousands): 1391045

```{r}
ledger |>
  filter(
    !is_nonbudgetary, !is_osse, !is_summeradvance, !is_capital, !is_medicaid
  ) |>
  summarize(ending_balance = sum(ending_balance))
```

```{r}
nonbudgetary <-
  ledger |>
  filter(is_nonbudgetary) |>
  summarize(ending_balance = sum(ending_balance))

osse <-
  ledger |>
  filter(is_osse) |>
  summarize(ending_balance = sum(ending_balance))

summeradvance <-
  ledger |>
  filter(is_summeradvance) |>
  summarize(ending_balance = sum(ending_balance))

capital <-
  ledger |>
  filter(is_capital) |>
  summarize(ending_balance = sum(ending_balance))

medicaid <-
  ledger |>
  filter(is_medicaid) |>
  summarize(ending_balance = sum(ending_balance))
```

```{r}
ledger |>
  summarize(ending_balance = sum(ending_balance)) |>
  bind_rows(
    nonbudgetary,
    osse,
    summeradvance,
    capital,
    medicaid
  )
```

```{r}
ledger |>
  summarize(ending_balance = sum(ending_balance), .by = account_category_desc)
```

```{r}
Sys.time()
```
