---
title: "Script 00: Clean R071"
format: html
---

```{r}
library(tidyverse)
library(glue)
library(janitor)
library(readxl)
library(writexl)

options(scipen = 12, digits = 12)
```

Setup

```{r}
path_data <- glue(
  "C:/Users",
  "{Sys.getenv('USERNAME')}",
  "OneDrive - District of Columbia Public Schools",
  "Data",
  .sep = "/"
)

fy <- "2024"

dir_r071 <- glue("{path_data}/Purchase Orders/R071/raw/{fy}")

path_r209 <-
  glue("{path_data}/Budget/R209/raw/{fy}/r209_GD0_GA0_{fy}.xlsx")

path_r071_ga0 <-
  glue("{dir_r071}/r071_GA0_{fy}.xls")

path_r071_gd0 <-
  glue("{dir_r071}/r071_GD0_{fy}.xls")
```

Read

209

```{r}
r209_raw <-
  read_excel(path_r209, col_types = "text", range = "A17:AG5216") %>%
  clean_names()

r209 <- r209_raw
```

R071

```{r}
r071_ga0 <-
  read_excel(path_r071_ga0, col_types = "text", range = "A23:AY8171") %>%
  clean_names()

r071_gd0 <-
  read_excel(path_r071_gd0, col_types = "text", range = "A23:AY5118") %>%
  clean_names()

r071_raw <- bind_rows(r071_ga0, r071_gd0)

r071 <- r071_raw
```

Rename

```{r}
r071_rename <- r071
```

Clean and transform

```{r}
r071_clean <-
  r071_rename %>%
  filter(buyer_agency == "GA0" | (project %in% r209$project)) %>%
  group_by(supplier_name, po_number, po_title) %>%
  summarize(
    cost_center_description = str_flatten(
      sort(unique(cost_center_description))[1:3],
      collapse = "; ",
      na.rm = TRUE
    ),
    po_line_item_description = str_flatten(
      sort(unique(po_line_item_description))[1:3],
      collapse = "; ",
      na.rm = TRUE
    ),
  ) %>%
  select(
    supplier_name, cost_center_description,
    po_title, po_line_item_description, po_number,
  ) %>%
  arrange(
    supplier_name, cost_center_description,
    po_title, po_line_item_description, po_number,
  )
```

Write

```{r}
r071_clean %>% write_xlsx("data/r071_clean.xlsx")
```
