---
title: "Clean Non-Personnel"
format: html
---

# Setup

```{r}
library(tidyverse)
library(glue)
library(janitor)
library(readxl)
library(writexl)
library(arrow)

options(scipen = 12, digits = 12)

path_data <- Sys.getenv("PATH_DATA")
year_fiscal <- Sys.getenv("YEAR_FISCAL")
```

# Import

Cost center categorization.

```{r}
costcenters <-
  read_excel(glue("{path_data}/manual/costcenters_categorization.xlsx")) |>
  select(costcenter_id, is_school)

previous <-
  read_csv(
    glue("{path_data}/previous/nonpersonnel_previous.csv"),
    col_types = cols(.default = col_character())
  ) |>
  filter(!is.na(po_number)) |>
  distinct(
    po_number,
    cat_prev = cat_po
  ) |>
  mutate(cat_prev = case_when(
    cat_prev == "Direct" ~ "direct",
    cat_prev == "Indirect" ~ "indirect",
    cat_prev == "Excluded" ~ "excluded",
  ))

previous |> count(cat_prev)
```

Grants

```{r}
awards <-
  read_parquet(glue("{path_data}/working/ledger.parquet")) |>
  distinct(award_id, project_id) |>
  filter_out(award_id == "1000074" & project_id != "400308")

grants <-
  read_excel(
    glue("{path_data}/manual/grants.xlsx"),
    col_types = "text"
  ) |>
  select(!c(projects_include, projects_exclude)) |>
  pivot_longer(
    cols = starts_with("award_id"),
    names_to = "award_type", names_prefix = "award_id_",
    values_to = "award_id", values_drop_na = TRUE
  ) |>
  mutate(is_grant = TRUE) |>
  select(!award_type) |>
  arrange(award_id, grant_name)

grants_lookup <-
  awards |>
  left_join(grants, by = join_by(award_id)) |>
  filter(!is.na(grant_name)) |>
  arrange(grant_name, award_id, project_id)
```

Raw non-personnel data.

```{r}
nonpersonnel_ga0 <-
  read_excel(
    glue("{path_data}/raw/r051a_expense_71_GA0_{year_fiscal}.xlsx"),
    range = "A13:AU46857",
    col_types = c(rep("text", 36), rep("numeric", 3), rep("text", 8))
  )

nonpersonnel_gd0 <-
  read_excel(
    glue("{path_data}/raw/r051a_expense_71_GD0_{year_fiscal}.xlsx"),
    range = "A13:AU60710",
    col_types = c(rep("text", 36), rep("numeric", 3), rep("text", 8))
  )

r209 <-
  read_excel(
    glue("{path_data}/raw/r209_GD0_GA0_{year_fiscal}.xlsx"),
    range = "A17:AG3974",
    col_types = "text"
  ) |>
  clean_names() |>
  rename(project_id = project)
```

Purchase order details.

```{r}
po <-
  read_excel(
    glue("{path_data}/raw/r071_2022_2026.xls"),
    range = "A23:AY40447",
    col_types = "text"
  ) |>
  clean_names() |>
  summarize(
    suppliers = str_flatten(
      sort(unique(supplier_name)),
      collapse = "; "
    ),
    items = str_flatten(
      sort(unique(po_line_item_description)),
      collapse = "; "
    ),
    .by = c(po_number, po_title)
  ) |>
  rename(title = po_title)
```

# Tidy and Transform

```{r}
nonpersonnel <-
  bind_rows(nonpersonnel_ga0, nonpersonnel_gd0) |>
  clean_names() |>
  rename(
    agency_id = agency,
    program_id = program, program_name = program_desc,
    costcenter_id = cost_center, costcenter_name = cost_center_desc,
    account_id = account, account_name = account_desc,
    project_id = project, project_name = project_desc,
    award_id = award, award_name = award_desc
  ) |>
  left_join(costcenters, by = join_by(costcenter_id)) |>
  mutate(
    costcenter_id = case_when(
      is_school ~ "SCHOOL",
      costcenter_id %in% c("10001", "10002", "10003", "10040") ~ "OCFO",
      costcenter_id %in% c("40078", "40203") ~ "40078",
      costcenter_id %in% c(
        "40080", "40084", "40130", "40208", "40228", "40229", "40242"
      ) ~ "OTHER DIRECT",
      costcenter_id %in% c("00000", "40223") ~ "OTHER INDIRECT",
      .default = costcenter_id
    ),
    costcenter_name = case_when(
      costcenter_id == "SCHOOL" ~ "SCHOOL",
      costcenter_id == "OCFO" ~ "OFFICE OF THE CHIEF FINANCIAL OFFICER",
      costcenter_id == "40078" ~ "OFFICE OF OPERATIONS",
      costcenter_id == "OTHER DIRECT" ~ "OTHER DIRECT",
      costcenter_id == "OTHER INDIRECT" ~ "OTHER INDIRECT",
      .default = costcenter_name
    ),
  ) |>
  filter(agency_id == "GA0" | ((project_id %in% r209$project_id))) |>
  filter(net_accounted != 0.00)
```

```{r}
costcenters_nonzero <-
  nonpersonnel |>
  summarize(
    net_accounted = round(sum(net_accounted), 2),
    .by = costcenter_id
  ) |>
  filter(net_accounted != 0.00)

nonpersonnel <-
  nonpersonnel |>
  filter(costcenter_id %in% costcenters_nonzero$costcenter_id)

nonpersonnel |>
  pull(net_accounted) |>
  sum()
```

Account ID's starting with 7131 or 7132, but that are not services.

```{r}
services_excluded <- c(
  "7131002",
  "7131003",
  "7131004",
  "7131007",
  "7131012",
  "7131014",
  "7131015",
  "7131017",
  "7131019",
  "7131020",
  "7131024",
  "7131025",
  "7131033",
  "7131045",
  "7132004"
)
```

```{r}
nonpersonnel_clean <-
  nonpersonnel |>
  left_join(grants_lookup, by = join_by(award_id, project_id)) |>
  mutate(is_capital = case_when(
    appropriation_fund == "3030" ~ TRUE,
    .default = FALSE
  )) |>
  mutate(is_service = when_all(
    str_detect(account_id, "^713[12]"),
    !(account_id %in% services_excluded)
  )) |>
  mutate(po_number = str_extract(
    transaction_id, regex("PO[:digit:]{6}", ignore_case = FALSE)
  )) |>
  mutate(is_po = !is.na(po_number), .before = po_number)
```

```{r}
nonpersonnel_clean |>
  write_parquet(glue("{path_data}/working/nonpersonnel_clean.parquet"))
nonpersonnel_clean |>
  write_csv(glue("{path_data}/working/nonpersonnel_clean.csv"), na = "")
```

Write out purchase orders for manual review.

```{r}
nonpersonnel_po <-
  nonpersonnel_clean |>
  filter(is_po, is_service)

po_costcenters <-
  nonpersonnel_po |>
  summarize(
    costcenter_names = str_flatten(
      sort(unique(costcenter_name)),
      collapse = "; "
    ),
    .by = po_number
  )

po_accounts <-
  nonpersonnel_po |>
  summarize(
    net_accounted = sum(net_accounted), .by = c(po_number, account_id)
  ) |>
  pivot_wider(
    id_cols = po_number,
    names_from = account_id, values_from = net_accounted, names_sort = TRUE
  ) |>
  rowwise() |>
  mutate(po_total = sum(c_across(starts_with("713")), na.rm = TRUE)) |>
  ungroup()

po_detail <-
  po_costcenters |>
  left_join(po_accounts, by = join_by(po_number)) |>
  left_join(po, by = join_by(po_number)) |>
  left_join(previous, by = join_by(po_number)) |>
  mutate(categorization = NA_character_) |>
  mutate(likely_not_excluded = str_detect(items, regex(
    "name (of )*(the )*resource|resource name|personnel|staffing|temps",
    ignore_case = TRUE
  ))) |>
  relocate(
    c(
      categorization, cat_prev,
      suppliers, title, items, costcenter_names, likely_not_excluded,
      po_number, po_total
    ),
    .before = 0
  ) |>
  arrange(
    likely_not_excluded,
    suppliers, items, title, costcenter_names, po_number
  ) |>
  filter(po_total != 0.00)

po_detail |> write_csv(glue("{path_data}/working/po_detail.csv"), na = "")
```

# Diagnostic

```{r}
Sys.time()
```
