---
title: "Indirect Cost Rates"
format: html
---

```{r}
library(tidyverse)
library(glue)
library(readxl)
library(janitor)

options(scipen = 12, digits = 12)
```

Setup

```{r}
path_data <- glue(
  "C:/Users",
  "{Sys.getenv('USERNAME')}",
  "OneDrive - District of Columbia Public Schools",
  "Data",
  .sep = "/"
)

path_r209 <-
  glue("{path_data}/Budget/R209/raw/2024/r209_GD0_GA0_2024.xlsx")

path_r023_ga0 <-
  glue("{path_data}/General Ledger/R023/raw/2024/r023_expense_GA0_2024.xls")

path_r023_gd0 <-
  glue("{path_data}/General Ledger/R023/raw/2024/r023_expense_GD0_2024.xls")
```

Read

209

```{r}
r209_raw <-
  read_excel(path_r209, col_types = "text", range = "A17:AG5216") %>%
  clean_names()

r209 <- r209_raw
```

023

```{r}
r023_ga0 <-
  read_excel(path_r023_ga0, col_types = "text", range = "A15:AL53429") %>%
  clean_names()

r023_gd0 <-
  read_excel(path_r023_gd0, col_types = "text", range = "A15:AL9711") %>%
  clean_names()

r023_raw <- bind_rows(r023_ga0, r023_gd0)

r023 <- r023_raw
```

Rename

```{r}
r023_rename <-
  r023 %>%
  rename(
    fund_number  = fund_detail,
    award_number = award
  )
```

Clean and transform

```{r}
r023_clean <-
  r023_rename %>%
  mutate(across(ending_balance, \(x) round(as.numeric(x), 2))) %>%
  mutate(
    is_osse = (agency == "GD0"),
    is_nonbudgetary = (award_number == "9999998"),
    is_summeradvance = (fund_number %in% c("1010171", "1010173")),
    is_capital = (appropriation_fund == "3030"),
    is_medicaid = (fund_number == "4020999" & award_number == "2000276")
  ) %>%
  filter(agency == "GA0" | (project %in% r209$project))
```

```{r}
osse <-
  r023_clean %>%
  filter(is_osse) %>%
  summarize(ending_balance = sum(ending_balance))

nonbudgetary <-
  r023_clean %>%
  filter(is_nonbudgetary) %>%
  summarize(ending_balance = sum(ending_balance))

summeradvance <-
  r023_clean %>%
  filter(is_summeradvance) %>%
  summarize(ending_balance = sum(ending_balance))

capital <-
  r023_clean %>%
  filter(is_capital) %>%
  summarize(ending_balance = sum(ending_balance))

r023_clean %>%
  summarize(ending_balance = sum(ending_balance)) %>%
  bind_rows(
    osse,
    nonbudgetary,
    summeradvance,
    capital
  )
```

Budgetary basis expenditures from ACFR (thousands): 1244373

```{r}
r023_clean %>%
  filter(!is_osse, !is_nonbudgetary, !is_summeradvance, !is_capital) %>%
  summarize(ending_balance = sum(ending_balance) %/% 1000)
```

```{r}

r023_clean %>% 
  group_by(account_category_desc) %>% 
  summarize(ending_balance = sum(ending_balance))

```

```{r}
r023_clean %>%
  writexl::write_xlsx("data/r023_clean.xlsx")
```
