---
title: "Categorize Non-Personnel"
format: html
---

```{r}
library(tidyverse)
library(glue)
library(janitor)
library(readxl)
library(writexl)

options(scipen = 12, digits = 12)
```

# Setup

```{r}
path_data <- glue(
  "C:/Users",
  "{Sys.getenv('USERNAME')}",
  "OneDrive - District of Columbia Public Schools",
  "Data",
  .sep = "/"
)

path_working <- glue(
  "C:/Users",
  "{Sys.getenv('USERNAME')}",
  "OneDrive - District of Columbia Public Schools",
  "Working Files - Indirect Cost",
  .sep = "/"
)
```

# Import

```{r}
nonpersonnel <-
  read_csv(
    "data/csv/nonpersonnel.csv",
    col_types = cols(net_accounted = col_double(), .default = col_character())
  )

personnel <-
  read_csv(
    "data/csv/personnel.csv",
    col_types = "c",
    col_select = c(costcenter_clean, categorization, costcenter_name_clean)
  )

accounts <-
  read_excel(
    glue("{path_working}/Categorization - Account.xlsx")
  ) %>%
  select(!c(account_desc, is_always_direct, is_always_indirect))

cat_po <-
  read_excel(
    glue("{path_working}/Categorization - PO.xlsx")
  ) %>%
  distinct(po_number, account, cat_po)
```

# Personnel proportions by cost center

```{r}
costcenters_missing <-
  tribble(
    ~costcenter_clean, ~categorization,
    "10040", "Indirect", # budget division, education cluster,
    "40208", "Direct", # enrollment and residency
    "40219", "Direct", # child care subsidy program,
    "40229", "Direct", # nutrition programs
    "40233", "Direct", # special education
  )
```

```{r}
props_costcenter <-
  personnel %>%
  select(!costcenter_name_clean) %>%
  bind_rows(costcenters_missing) %>%
  count(costcenter_clean, categorization) %>%
  group_by(costcenter_clean) %>%
  mutate(prop = n / sum(n)) %>%
  select(!n) %>%
  pivot_wider(
    id_cols = costcenter_clean,
    names_from = categorization,
    values_from = prop,
    values_fill = 0.0
  ) %>%
  select(costcenter_clean, prop_direct = Direct, prop_indirect = Indirect)
```

Occupancy proportions

```{r}
occupancy_central <- 
  personnel %>%
  filter(
    !(costcenter_clean %in% c("SCHOOLS", "40104", "40231", "40232")),
    !(costcenter_clean == "40077" & categorization == "Direct")
  ) %>% 
  count(categorization) %>% 
  mutate(prop = n / sum(n)) %>%
  select(!n) %>%
  pivot_wider(
    names_from = categorization,
    values_from = prop,
    values_fill = 0.0
  ) %>% 
  mutate(is_occupancy_central = 1) %>% 
  rename(prop_central_direct = Direct, prop_central_indirect = Indirect)

occupancy_overall <- 
  personnel %>%
  count(categorization) %>% 
  mutate(prop = n / sum(n)) %>%
  select(!n) %>%
  pivot_wider(
    names_from = categorization,
    values_from = prop,
    values_fill = 0.0
  ) %>% 
  mutate(is_occupancy_overall = 1) %>% 
  rename(prop_overall_direct = Direct, prop_overall_indirect = Indirect)

```

#

```{r}
nonpersonnel_cat <-
  nonpersonnel %>%
  left_join(cat_po, by = join_by(po_number, account)) %>%
  left_join(accounts, by = join_by(account)) %>%
  left_join(props_costcenter, by = join_by(costcenter_clean)) %>%
  left_join(occupancy_central, by = join_by(is_occupancy_central)) %>%
  left_join(occupancy_overall, by = join_by(is_occupancy_overall)) %>%
  # cleanup
  mutate(
    is_excluded = case_when(
      is_capital == "TRUE" ~ 1,
      .default = is_excluded
    )
  ) %>%
  #
  mutate(
    amt_nonbudgetary = if_else(is_nonbudgetary == 1, net_accounted, 0, missing = 0),
    amt_unallowable = if_else(is_unallowable == 1, net_accounted, 0, missing = 0)
  ) %>%
  mutate(amt_excluded = case_when(
    is_nonbudgetary == 1 ~ 0.00,
    is_unallowable == 1 ~ 0.00,
    is_po == "TRUE" & cat_po == "Excluded" ~ net_accounted,
    is_po == "FALSE" & is_occupancy == 1 ~ 0.00,
    is_po == "FALSE" & is_excluded == 1 ~ net_accounted,
    .default = 0.00
  )) %>%
  mutate(amt_direct = case_when(
    is_po == "TRUE" & cat_po == "Direct" ~ net_accounted,
    is_po == "TRUE" ~ 0.00,
    is_po == "FALSE" & is_occupancy_central == 1 ~ net_accounted * prop_central_direct,
    is_po == "FALSE" & is_occupancy_overall == 1 ~ net_accounted * prop_overall_direct,
    is_po == "FALSE" & is_excluded == 1 ~ 0.00,
    is_nonbudgetary == 1 ~ 0.00,
    is_unallowable == 1 ~ 0.00,
    .default = net_accounted * prop_direct
  )) %>%
  mutate(amt_indirect = case_when(
    is_po == "TRUE" & cat_po == "Indirect" ~ net_accounted,
    is_po == "TRUE" ~ 0.00,
    is_po == "FALSE" & is_occupancy_central == 1 ~ net_accounted * prop_central_indirect,
    is_po == "FALSE" & is_occupancy_overall == 1 ~ net_accounted * prop_overall_indirect,
    is_po == "FALSE" & is_excluded == 1 ~ 0.00,
    is_nonbudgetary == 1 ~ 0.00,
    is_unallowable == 1 ~ 0.00,
    .default = net_accounted * prop_indirect
  )) %>%
  mutate(
    amt_total = amt_nonbudgetary + amt_unallowable + amt_excluded + amt_direct + amt_indirect
  ) %>%
  filter(!is.na(amt_total))
```

```{r}
nonpersonnel_cat %>% write_csv("data/csv/nonpersonnel_cat.csv", na = "")
```

# Diagnostics

```{r}
nonpersonnel_cat %>%
  pull(amt_total) %>%
  sum()
```

```{r}
nonpersonnel_cat %>%
  filter(is.na(amt_total)) %>%
  group_by(costcenter_clean, costcenter_name_clean, account_name) %>%
  summarize(
    net_accounted = sum(net_accounted), n_transactions = n(),
    .groups = "drop"
  )
```

```{r}
Sys.time()
```
