---
title: "Generate Schedules"
format: html
---

```{r}
library(tidyverse)
library(glue)
library(janitor)
library(readxl)
library(writexl)

options(scipen = 12, digits = 12)
```

Setup

```{r}
path_data <- glue(
  "C:/Users",
  "{Sys.getenv('USERNAME')}",
  "OneDrive - District of Columbia Public Schools",
  "Data",
  .sep = "/"
)
```

Read

```{r}
ledger <- read_csv(
  "data/csv/ledger.csv",
  col_types = cols(ending_balance = col_double(), .default = col_character())
)

personnel_categorized <-
  read_csv(
    "data/csv/personnel.csv",
    col_types = cols(
      amt_salary = col_double(),
      amt_benefits = col_double(),
      amt_direct = col_double(),
      amt_indirect = col_double(),
      amt_total = col_double(),
      amt_unrestricted = col_double(),
      amt_headcomponent_direct = col_double(),
      amt_headcomponent_indirect = col_double(),
      amt_headcomponent_total = col_double(),
      amt_terminal = col_double(),
      amt_terminal_to_indirect = col_double(),
      amt_terminal_restricted = col_double(),
      .default = col_character()
    )
  )

nonpersonnel_categorized <-
  read_csv(
    "data/csv/nonpersonnel_cat.csv",
    col_types = cols(
      amt_nonbudgetary = col_double(),
      amt_unallowable = col_double(),
      amt_excluded = col_double(),
      amt_direct = col_double(),
      amt_indirect = col_double(),
      amt_total = col_double(),
      .default = col_character()
    )
  )
```

A

```{r}
personnel_by_costcenter <-
  personnel_categorized %>%
  group_by(costcenter_clean) %>%
  summarize(
    amt_direct_ps = sum(amt_direct),
    amt_indirect_ps = sum(amt_indirect),
    amt_total_ps = sum(amt_total),
    .groups = "drop"
  )

nonpersonnel_by_costcenter <-
  nonpersonnel_categorized %>%
  group_by(costcenter_clean) %>%
  summarize(
    amt_nonbudgetary = sum(amt_nonbudgetary),
    amt_unallowable = sum(amt_unallowable),
    amt_excluded = sum(amt_excluded),
    amt_direct_nps = sum(amt_direct),
    amt_indirect_nps = sum(amt_indirect),
    .groups = "drop"
  ) %>%
  mutate(
    amt_budgetary = amt_unallowable + amt_excluded + amt_direct_nps + amt_indirect_nps,
    amt_unallowable_excluded = amt_unallowable + amt_excluded,
    amt_total_nps = amt_nonbudgetary + amt_unallowable + amt_excluded + amt_direct_nps + amt_indirect_nps,
  )

schedule_a <-
  bind_rows(
    select(personnel_categorized, costcenter_name_clean, costcenter_clean),
    select(nonpersonnel_categorized, costcenter_name_clean, costcenter_clean)
  ) %>%
  distinct() %>%
  left_join(personnel_by_costcenter, by = join_by(costcenter_clean)) %>%
  left_join(nonpersonnel_by_costcenter, by = join_by(costcenter_clean)) %>%
  mutate(across(where(is_double), \(x) replace_na(x, 0.00))) %>%
  mutate(
    amt_direct = amt_direct_ps + amt_direct_nps,
    amt_indirect = amt_indirect_ps + amt_indirect_nps,
    amt_total = amt_total_ps + amt_total_nps
  ) %>%
  select(
    costcenter_clean, costcenter_name_clean,
    amt_total, amt_unallowable_excluded,
    amt_direct_ps, amt_direct_nps, amt_direct,
    amt_indirect_ps, amt_indirect_nps, amt_indirect
  ) %>%
  arrange(costcenter_name_clean)

schedule_a %>% write_xlsx("schedules/schedule_a.xlsx")
```

D.1

```{r}
schedule_d1 <-
  personnel_categorized %>%
  select(!starts_with("amt_terminal")) %>%
  group_by(
    costcenter_name_clean, categorization,
    name_clean, title, headcomponent,
  ) %>%
  summarize(
    amt_salary = sum(amt_salary),
    amt_benefits = sum(amt_benefits),
    amt_direct = sum(amt_direct),
    amt_indirect = sum(amt_indirect),
    amt_unrestricted = sum(amt_unrestricted),
    amt_headcomponent_direct = sum(amt_headcomponent_direct),
    amt_headcomponent_indirect = sum(amt_headcomponent_indirect),
    amt_headcomponent_total = sum(amt_headcomponent_total),
    .groups = "drop"
  ) %>%
  relocate(categorization)

schedule_d1 %>% write_xlsx("schedules/schedule_d1.xlsx")
```

D.2

```{r}
fringe_other <- c(
  "DC METRO BENEFITS",
  "MISC FRINGE BENEFITS",
  "RETIREMENT CONTRIBUTION - CIVIL SERVICE",
  "RETIREMENT CONTRIBUTION - TEACHERS",
  "UNEMPLOYMENT INSURANCE"
)

fringe <-
  ledger %>%
  filter(account_class_desc == "FRINGE BENEFITS - CURR PERSONNEL") %>%
  mutate(
    account_name = if_else(
      account_name %in% fringe_other, "OTHER", account_name
    )
  ) %>%
  group_by(account_name) %>%
  summarize(ending_balance = sum(ending_balance)) %>%
  mutate(is_other = account_name == "OTHER") %>%
  arrange(is_other, desc(ending_balance))

fringe_total <-
  fringe %>%
  summarize(ending_balance = sum(ending_balance)) %>%
  mutate(account_name = "TOTAL", .before = 0)

schedule_d2 <-
  fringe %>%
  filter(ending_balance != 0.00) %>%
  bind_rows(fringe_total) %>%
  select(!is_other)

schedule_d2 %>% write_xlsx("schedules/schedule_d2.xlsx")

personnel_categorized %>%
  group_by(categorization) %>%
  summarize(amt_benefits = sum(amt_benefits), .groups = "drop")
```

E

```{r}
schedule_e <-
  personnel_categorized %>%
  filter(amt_terminal != 0.00) %>%
  select(!c(
    amt_salary, amt_benefits, amt_total,
    amt_direct, amt_indirect, amt_unrestricted,
    amt_headcomponent_direct, amt_headcomponent_indirect, amt_headcomponent_total
  )) %>%
  group_by(
    costcenter_name_clean, categorization,
    name_clean, title, headcomponent,
  ) %>%
  summarize(
    amt_terminal = sum(amt_terminal),
    amt_terminal_unrestricted = sum(amt_terminal_to_indirect),
    amt_terminal_restricted = sum(amt_terminal_restricted),
    .groups = "drop"
  ) %>%
  relocate(categorization)

schedule_e %>% write_xlsx("schedules/schedule_e.xlsx")
```

F

```{r}
schedule_f <-
  nonpersonnel_categorized %>%
  filter(is_po == TRUE) %>%
  group_by(costcenter_name_clean, po_number, party_name) %>%
  summarize(
    amt_total = sum(amt_total),
    amt_unallowable = sum(amt_unallowable),
    amt_excluded = sum(amt_excluded),
    amt_direct = sum(amt_direct),
    amt_indirect = sum(amt_indirect),
    .groups = "drop"
  ) %>%
  filter(amt_total != 0.00) %>%
  mutate(note = case_when(
    amt_direct != 0.00 & amt_indirect != 0.00 ~ "Subaward consists of both direct and indirect services.",
    amt_direct != 0.00 ~ "Some expenses moved to Direct Cost Pool for provision of FTE-like services.",
    amt_indirect != 0.00 ~ "Some expenses moved to Indirect Cost Pool for agency-wide indirect services.",
    .default = NA_character_
  ))

schedule_f %>% write_xlsx("schedules/schedule_f.xlsx")
```

Schedule H: Occupancy

```{r}
occupancy <-
  nonpersonnel_categorized %>%
  filter(is_occupancy == 1)

occupancy_total <-
  occupancy %>%
  summarize(
    amt_total = sum(amt_total),
    amt_direct = sum(amt_direct),
    amt_indirect = sum(amt_indirect)
  ) %>%
  mutate(account_name = "OCCUPANCY TOTAL")

schedule_h <-
  occupancy %>%
  group_by(account_name) %>%
  summarize(
    amt_total = sum(amt_total),
    amt_direct = sum(amt_direct),
    amt_indirect = sum(amt_indirect)
  ) %>%
  arrange(desc(amt_total)) %>%
  bind_rows(occupancy_total)

schedule_h %>% write_xlsx("schedules/schedule_h.xlsx")
```

I

```{r}
schedule_i <-
  nonpersonnel_categorized %>%
  filter(amt_excluded != 0.00) %>%
  mutate(exclusion_type = case_when(
    !is.na(is_excluded_food) ~ "food",
    !is.na(is_excluded_equipment) ~ "equipment",
    !is.na(is_excluded_passthrough) ~ "passthrough",
    is_capital == "TRUE" ~ "capital",
    # is_grant == "TRUE" ~ "grant",
    is_po == "TRUE" ~ "subaward"
  )) %>%
  group_by(costcenter_name_clean, exclusion_type) %>%
  summarize(amt_excluded = sum(amt_excluded), .groups = "drop") %>%
  arrange((costcenter_name_clean), (amt_excluded)) %>%
  pivot_wider(
    names_from = exclusion_type,
    values_from = amt_excluded,
    names_sort = TRUE
  ) %>%
  mutate(across(where(is_double), \(x) replace_na(x, 0.00))) %>%
  relocate(c(capital, equipment, food, passthrough), .after = costcenter_name_clean)

schedule_i %>% write_xlsx("schedules/schedule_i.xlsx")
```

Schedule J: Indirect Costs

```{r}
schedule_j_indirect <-
  nonpersonnel_categorized %>%
  group_by(costcenter_name_clean) %>%
  summarize(amt_indirect = sum(amt_indirect), .groups = "drop") %>%
  filter(amt_indirect != 0.00) %>%
  arrange(costcenter_name_clean)

schedule_j_unallowable <-
  nonpersonnel_categorized %>%
  mutate(across(account_name, \(x) if_else(str_detect(x, "^INT "), "INT PENALTIES", account_name))) %>%
  group_by(costcenter_name_clean, account_name) %>%
  summarize(amt_unallowable = sum(amt_unallowable), .groups = "drop") %>%
  filter(amt_unallowable != 0.00) %>%
  arrange(account_name, costcenter_name_clean) %>%
  pivot_wider(names_from = account_name, values_from = amt_unallowable)

schedule_j <-
  schedule_j_indirect %>%
  full_join(schedule_j_unallowable, by = join_by(costcenter_name_clean)) %>%
  mutate(across(where(is_double), \(x) replace_na(x, 0.00))) %>%
  relocate(GENERAL, .after = amt_indirect) %>%
  arrange(costcenter_name_clean)

schedule_j %>% write_xlsx("schedules/schedule_j.xlsx")
```

K

```{r}
props_headcomponent <-
  personnel_categorized %>%
  group_by(costcenter_clean) %>%
  summarize(
    n_headcomponent = sum(headcomponent != "Non-executive" & categorization == "Indirect"),
    n_indirect = sum(categorization == "Indirect"),
    .groups = "drop"
  ) %>%
  filter(n_indirect > 0) %>%
  mutate(prop_headcomponent = n_headcomponent / n_indirect)

schedule_k <-
  nonpersonnel_categorized %>%
  filter(is_salaryadjustment == "1") %>%
  mutate(account_name = case_when(
    account_name %in% c("FUEL AUTOMOTIVE", "GAS") ~ "FUEL",
    account_name %in% c("IT HARDWARE ACQUISITIONS", "IT SOFTWARE ACQUISITIONS", "IT SUPPLIES") ~ "IT",
    account_name %in% c("TRAVEL - LOCAL", "TRAVEL - OUT OF CITY") ~ "TRAVEL",
    .default = account_name
  )) %>%
  group_by(costcenter_clean, costcenter_name_clean, account_name) %>%
  summarize(amt_indirect = sum(amt_indirect), .groups = "drop") %>%
  left_join(props_headcomponent, by = join_by(costcenter_clean)) %>%
  mutate(amt_salaryadjustment = prop_headcomponent * amt_indirect) %>%
  filter(!is.na(n_headcomponent), amt_salaryadjustment != 0.00) %>%
  select(!c(amt_indirect, n_headcomponent, n_indirect, prop_headcomponent)) %>%
  arrange(costcenter_name_clean) %>%
  pivot_wider(names_from = account_name, values_from = amt_salaryadjustment, names_sort = TRUE) %>%
  mutate(across(where(is_double), \(x) replace_na(x, 0.00)))

schedule_k %>% write_xlsx("schedules/schedule_k.xlsx")
```

```{r}
Sys.time()
```
